# Welcome to the Sandbox.
## A place to write and test random stuff

Double click into cells to edit them, this will transform markdown cells from their nicely formatted versions to the actual markdown script the first thing that we have here is a series of basic python scripts to make sure everything is running as expected.

In [ ]:
print('hello world')

#### The code below is just simple processing on a given list of integers. It makes use of python's ability to simplify 'and' expressions for integer ranges. Very nice.

In [ ]:
#Gatekeeper Code Exercise
population_ages = [10,4,18,12,16,20,26,100,24]
for age in population_ages:
    if age <= 6:
        print('You are ' + str(age) + ' years old and cannot enter')
    elif 6 < age <= 12:
        print('You are ' + str(age) + ' years old and can enter child friendly areas')
    elif 12 < age <= 16:
        print('You are ' + str(age) + ' years old and can enter with an adult')
    elif age >= 17:
        print('You are ' + str(age) + ' years old and can enter freely')
    else:
        print('somehow palpatine returned?')

## Challenge:
Write a login program that asks a user for username and password, which are predefined. Full brief [**here**](https://vle.aston.ac.uk/ultra/courses/_62426_1/outline/edit/document/_4285221_1?courseId=_62426_1&view=content&state=view)

In [ ]:
#set up a login bools for while loop
good_login:bool = False
attempts:int = 0
while not good_login and attempts < 3:
    #Request username
    username:str = input("Enter your username: ")
    #Request password
    password:str = input("Enter your password: ")
    if username == 'admin' and password == 'password123':
        print('You are logged in')
        good_login = True
    elif username.lower() == 'quit' and password.lower() == '':
        break
    else:
        attempts += 1
        if attempts < 3:
            print("You are not logged in and have %d attempts left, check your username and password and try again or enter username: QUIT password: *blank* to exit the application" % (3-attempts))
print('Allowed attempts exceeded or an error occurred. Please try again later')

# Course Work Data Playground

In [13]:
import pandas as pd
import pandasql as ps

#Read in the whole CSV.
df_all = pd.read_csv("CW_data.csv", encoding='ANSI')
df_all.shape

(3999, 108)

In [8]:
df_all.head()

,Patient ID,Patient age quantile,feat_Hematocrit,feat_Hemoglobin,feat_Platelets,feat_Mean platelet volume,feat_Red blood Cells,feat_Lymphocytes,feat_Mean corpuscular hemoglobin concentration (MCHC),feat_Leukocytes,...,feat_pCO2 (arterial blood gas analysis),feat_Base excess (arterial blood gas analysis),feat_pH (arterial blood gas analysis),feat_Total CO2 (arterial blood gas analysis),feat_HCO3 (arterial blood gas analysis),feat_pO2 (arterial blood gas analysis),feat_Arteiral Fio2,feat_Phosphor,feat_ctO2 (arterial blood gas analysis),SARS-Cov-2 exam result
0,715f6bdee94fdd7,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
1,4495129155a2cc9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
2,af17911deea7b00,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
3,e224cf1e494ed00,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative
4,e4a2898af91b43f,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,negative

Seems to be some useless columns with just values of NA. I could find a way to drop columns with all NA, but it might be worth dropping columns with all values that are identical, regardless of if they are NaN or not. I think this is the correct choice as a column with all the same value will likely not provide any good information for the model to interpret and find trends. It would also lead to issues when looking at the test data set as if a col in the development data is full of a single value but in the test data it has multiple values, the algorithm will not have sufficient knowledge to assess the weight of those other differing values. Therefore, exclude all cols that have only got one unique value.

In [14]:
df_single_values =  df_all.loc[:, df_all.nunique(dropna = False) == 1]
print(df_single_values.columns)

Index(['feat_Mycoplasma pneumoniae', 'feat_Fio2 (venous blood gas analysis)',
       'feat_Urine - Nitrite', 'feat_Urine - Sugar',
       'feat_Partial thromboplastin time (PTT) ',
       'feat_Prothrombin time (PT), Activity', 'feat_D-Dimer'],
      dtype='object')

In [9]:
df_single_values.head()

,feat_Mycoplasma pneumoniae,feat_Fio2 (venous blood gas analysis),feat_Urine - Nitrite,feat_Urine - Sugar,feat_Partial thromboplastin time (PTT),"feat_Prothrombin time (PT), Activity",feat_D-Dimer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#df_single_values.columns
df_filtered = df_all.drop(labels = df_single_values.columns, axis = 1)
df_filtered.dtypes
# df_numerics = df_filtered.select_dtypes(include = 'bool')
# print(df_numerics.columns)

Patient ID                                  object
Patient age quantile                         int64
feat_Hematocrit                            float64
feat_Hemoglobin                            float64
feat_Platelets                             float64
                                            ...
feat_pO2 (arterial blood gas analysis)     float64
feat_Arteiral Fio2                         float64
feat_Phosphor                              float64
feat_ctO2 (arterial blood gas analysis)    float64
SARS-Cov-2 exam result                      object
Length: 101, dtype: object